name: CI

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test_deploy:
      name: Build test and deploy only affected code
      timeout-minutes: 15
      runs-on: ${{ matrix.os }}
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      env:
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      strategy:
        matrix:
          os: [ubuntu-latest]

      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'yarn'

        - name: Install dependencies
          run: yarn
        
        - id: changes
          name: File Changes
          uses: tj-actions/changed-files@v23

        - name: Ouput Changed files
          run: |
            for file in ${{ steps.changes.outputs.all_changed_files }}; do
              echo $file
            done

        - name: Build and test ui-kit
          if: contains(steps.changes.outputs.all_changed_files, 'frontend/ui-kit/')
          run: yarn ui-kit build && yarn ui-kit test

        - name: Build and test admin-dashboard
          if: contains(steps.changes.outputs.all_changed_files, 'frontend/admin-dashboard/') || contains(steps.file_changes.outputs.files , '"frontend/uikit/')
          run: yarn admin-dashboard build && yarn admin-dashboard test
          
        - name: Build and test landing
          if: contains(steps.changes.outputs.all_changed_files, 'frontend/landing/') || contains(steps.file_changes.outputs.files , '"frontend/uikit/')
          run: yarn landing build && yarn landing test

        - name: Build and test db
          if: contains(steps.changes.outputs.all_changed_files, 'backend/db/')
          run: yarn db build && yarn db test

        - name: Build, test and deploy server
          if: contains(steps.changes.outputs.all_changed_files, 'backend/server/') || contains(steps.file_changes.outputs.files , '"backend/db/')
          run: yarn db build && yarn server build && yarn server test && zip -r backend/server/dist deploy.zip 

        - name: Deploy to Beanstalk
          if: contains(steps.changes.outputs.all_changed_files, 'backend/server/') || contains(steps.file_changes.outputs.files , '"backend/db/')
          uses: einaregilsson/beanstalk-deploy@v18
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: monolitik-server
            environment_name: Monolitikserver-env
            version_label: ${{ github.sha }}
            region: us-east-1
            use_existing_version_if_available: true
            deployment_package: deploy.zip