name: ci-frontend

on:
  push:
    # f/landing/add-seo
    # f/admin-dashboard/fix-login
    branches: ["main", "dev", "f/**"] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get_file_changes:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest]
    
    outputs:
      should_run: ${{ steps.should_run.outputs.value }}
      changes: ${{ steps.changes.outputs.all_changed_files }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - id: changes
        name: File Changes
        uses: tj-actions/changed-files@v23

      - name: Ouput Changed files
        run: |
          for file in ${{ steps.changes.outputs.all_changed_files }}; do
            echo $file
          done
      
      - id: should_run
        run: echo ::set-output name=value::${{ contains(steps.changes.outputs.all_changed_files, 'frontend/') }}

  build_test_deploy:
      needs: get_file_changes
      if: ${{ needs.get_file_changes.outputs.should_run == 'true' }}

      name: Build test and deploy frontend
      timeout-minutes: 15
      runs-on: ${{ matrix.os }}
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      env:
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      strategy:
        matrix:
          os: [ubuntu-latest]

      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'yarn'

        - name: Install dependencies
          run: yarn
          
        - name: Build and test ui-kit
          if: contains(needs.get_file_changes.outputs.changes, 'frontend/ui-kit/')
          run: yarn ui-kit build && yarn ui-kit test

        - name: Build and test admin-dashboard
          if: contains(needs.get_file_changes.outputs.changes, 'frontend/admin-dashboard/') || contains(needs.get_file_changes.outputs.changes, '"frontend/uikit/')
          run: yarn admin-dashboard build && yarn admin-dashboard test
          
        - name: Build and test landing
          if: contains(needs.get_file_changes.outputs.changes, 'frontend/landing/') || contains(needs.get_file_changes.outputs.changes, '"frontend/uikit/')
          run: yarn landing build && yarn landing test